/**
 * Canonical protobuf-ts codec, relocated from web-ui/src/app/generated/messages.ts
 * (ADR-0066 D2). This is the ONLY wire codec; the five previous hand-rolled copies
 * collapse into it. messages.ts imports ONLY `@protobuf-ts/runtime` — zero Angular,
 * zero browser globals — so it relocates verbatim and is safe in browser, Node, and
 * the Pulumi provider host alike.
 *
 * The generated file stays gitignored and is regenerated by the proto-gen step
 * before bundling (Phase 1 of the extraction plan).
 */
export * from './messages.js';
